### ISSUE TITLE
convert from http to https to allow audio recording

### ISSUE THREAD

**Issue by xmeatballx** [edubz/CapStoneServer#11]
@edubz think you could take a crack at this?

**Comment by edubz** [comment]
is this still a feature that we need? i've been looking into the https module recently and i think i could make it happen

**Comment by xmeatballx** [comment]
Yeah! Once we host it publicly it’ll need to be https to work. Thanks!

**Comment by xmeatballx** [comment]
Heroku handled that automatically

**Comment by jmej** [comment]
remember these work in commit messages https://gist.github.com/rxaviers/7360908 lol
