### ISSUE TITLE
deploy public server 

### ISSUE THREAD

**Issue by xmeatballx** [edubz/CapStoneServer#16]
look into different hosting options(heroku, amazon, hostgator?), choose one, and try to get the public server deployed

**Comment by edubz** [comment]
I've been using heroku lately. I like the workflow. but hostgator is great aswell, just depends on the specific needs of the project. not really 100 on the pros & cons of the 2

**Comment by jmej** [comment]
heroku is expensive but very fast and easy. amazon is probably cheaper but a lot more complex to deploy. i don't have any hostgator experience--but heroku is generally my choice for quick deploys
